// Code generated by packages/sdk-generator from packages/mcp/src. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:09aa9517f466027d023798abdf939204d057d808cb4eb15566deed6b960adcec
// MCP endpoint catalog: a compact, input-only view of the public OpenAPI contract that the MCP
// tools search, describe and invoke. Built from packages/api-contract/generated/openapi.json by
// scripts/api-contract.mjs (committed as packages/mcp/generated/catalog.json, drift-checked) and
// shipped inside the stdio package by packages/sdk-generator. Pure data; no runtime imports.

export type JsonSchema = Record<string, unknown>;

export interface CatalogParam {
  name: string;
  required: boolean;
  description: string;
  schema: JsonSchema;
}

export interface CatalogEndpoint {
  /** The contract operationId, for example `qbd.invoices.create`. */
  name: string;
  method: 'GET' | 'POST' | 'DELETE' | 'PUT' | 'PATCH';
  path: string;
  /** First contract tag, for example `Invoices`. */
  tag: string;
  /** x-tagGroups group of the tag, for example `Transactions`. */
  group: string;
  summary: string;
  description: string;
  /** Anything other than GET changes data (read-only keys are rejected by the API). */
  write: boolean;
  /** The operation requires the Daapi-End-User-Id header. */
  endUser: boolean;
  /** The operation accepts an Idempotency-Key header. */
  idempotent: boolean;
  pathParams: CatalogParam[];
  queryParams: CatalogParam[];
  /** JSON request body, when the operation takes one. `schema` may contain `$ref: #/$defs/<name>`. */
  body: { required: boolean; schema: JsonSchema } | null;
}

export interface Catalog {
  apiVersion: string;
  servers: { url: string; description: string }[];
  endpoints: CatalogEndpoint[];
  /** Every component schema reachable from an endpoint input, keyed by component name. */
  defs: Record<string, JsonSchema>;
}

type Obj = Record<string, unknown>;
const METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const;

function deref(doc: Obj, value: unknown): Obj {
  let v = value as Obj;
  for (let i = 0; i < 10 && v && typeof v.$ref === 'string'; i++) {
    const parts = (v.$ref as string).replace(/^#\//, '').split('/');
    let cur: unknown = doc;
    for (const p of parts) cur = (cur as Obj)[p];
    v = cur as Obj;
  }
  return v;
}

/** Rewrites component refs to `#/$defs/<name>` and records the referenced names. */
function rewrite(value: unknown, seen: Set<string>): unknown {
  if (Array.isArray(value)) return value.map((v) => rewrite(v, seen));
  if (!value || typeof value !== 'object') return value;
  const out: Obj = {};
  for (const [k, v] of Object.entries(value as Obj)) {
    if (k === '$ref' && typeof v === 'string' && v.startsWith('#/components/schemas/')) {
      const name = v.slice('#/components/schemas/'.length);
      seen.add(name);
      out.$ref = `#/$defs/${name}`;
    } else if (k === 'example' || k === 'examples') {
      // Examples stay: they show agents the expected shape.
      out[k] = v;
    } else out[k] = rewrite(v, seen);
  }
  return out;
}

export function buildCatalog(doc: Obj): Catalog {
  const groups = new Map<string, string>();
  for (const g of (doc['x-tagGroups'] as { name: string; tags: string[] }[] | undefined) ?? []) for (const t of g.tags) groups.set(t, g.name);
  const pending = new Set<string>();
  const endpoints: CatalogEndpoint[] = [];
  for (const [path, item] of Object.entries(doc.paths as Obj)) {
    for (const method of METHODS) {
      const op = (item as Obj)[method] as Obj | undefined;
      if (!op) continue;
      const pathParams: CatalogParam[] = [];
      const queryParams: CatalogParam[] = [];
      let endUser = false;
      let idempotent = false;
      for (const raw of (op.parameters as unknown[] | undefined) ?? []) {
        const p = deref(doc, raw);
        if (p.in === 'header') {
          if (p.name === 'Daapi-End-User-Id') endUser = true;
          if (p.name === 'Idempotency-Key') idempotent = true;
          continue;
        }
        const schema = { ...(rewrite(p.schema, pending) as Obj) };
        if (schema.description === p.description) delete schema.description;
        const param: CatalogParam = { name: String(p.name), required: p.required === true, description: String(p.description ?? ''), schema };
        if (p.in === 'path') pathParams.push(param);
        else if (p.in === 'query') queryParams.push(param);
      }
      const rb = op.requestBody ? deref(doc, op.requestBody) : undefined;
      const json = (rb?.content as Obj | undefined)?.['application/json'] as Obj | undefined;
      const tag = String((op.tags as string[])[0]);
      endpoints.push({
        name: String(op.operationId),
        method: method.toUpperCase() as CatalogEndpoint['method'],
        path,
        tag,
        group: groups.get(tag) ?? 'Other',
        summary: String(op.summary ?? ''),
        description: String(op.description ?? ''),
        write: method !== 'get',
        endUser,
        idempotent,
        pathParams,
        queryParams,
        body: json ? { required: rb?.required === true, schema: rewrite(json.schema, pending) as Obj } : null,
      });
    }
  }
  const schemas = ((doc.components as Obj).schemas ?? {}) as Obj;
  const defs: Record<string, JsonSchema> = {};
  while (pending.size) {
    const [name] = pending;
    pending.delete(name!);
    if (defs[name!]) continue;
    const found = new Set<string>();
    defs[name!] = rewrite(schemas[name!], found) as JsonSchema;
    for (const n of found) if (!defs[n]) pending.add(n);
  }
  const sortedDefs: Record<string, JsonSchema> = {};
  for (const k of Object.keys(defs).sort()) sortedDefs[k] = defs[k]!;
  return {
    apiVersion: String((doc.info as Obj).version),
    servers: (doc.servers as { url: string; description: string }[]) ?? [],
    endpoints,
    defs: sortedDefs,
  };
}

/** The `$defs` an input schema needs, transitively. */
export function defsFor(catalog: Catalog, roots: unknown[]): Record<string, JsonSchema> {
  const out: Record<string, JsonSchema> = {};
  const visit = (v: unknown): void => {
    if (Array.isArray(v)) return v.forEach(visit);
    if (!v || typeof v !== 'object') return;
    for (const [k, x] of Object.entries(v as Obj)) {
      if (k === '$ref' && typeof x === 'string' && x.startsWith('#/$defs/')) {
        const name = x.slice('#/$defs/'.length);
        if (!out[name] && catalog.defs[name]) {
          out[name] = catalog.defs[name]!;
          visit(catalog.defs[name]);
        }
      } else visit(x);
    }
  };
  roots.forEach(visit);
  return out;
}
