#!/usr/bin/env node
// Code generated by packages/sdk-generator from packages/mcp/src. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:d4adaec794b6cf028d0f87bcaed3668ec305d5e364a02008e8a22258ee3a7d59
// Local (stdio) MCP server for the Desktop Accounting API.
//
//   npx -y @desktopaccountingapi/quickbooks-desktop-mcp [--read-only] [--resources invoices,customers] [--end-user-id eu_...]
//
// Environment: DAAPI_SECRET_KEY (required for API calls), DAAPI_BASE_URL (default
// https://api.desktopaccountingapi.com), DAAPI_END_USER_ID, DAAPI_MCP_READ_ONLY=true,
// DAAPI_MCP_RESOURCES, DAAPI_DOCS_URL.

import { existsSync, readFileSync } from 'node:fs';
import type { Catalog } from './catalog.ts';
import { McpServer } from './server.ts';
import { serveStdio } from './stdio.ts';

const HELP = `Desktop Accounting API MCP server (stdio)

Usage: quickbooks-desktop-mcp [options]

Options:
  --read-only             Hide and refuse operations that change data. For a limit
                          the API enforces, use a read-only secret key.
                          (--code-allow-http-gets, Conductor's flag, is an alias.)
  --resources <list>      Also expose one tool per operation for these resources
                          (for example invoices,customers or all).
  --end-user-id <eu_...>  Default end user for QuickBooks operations.
  --base-url <url>        API origin (default https://api.desktopaccountingapi.com).
  --version               Print the version.
  --help                  Print this help.

Environment: DAAPI_SECRET_KEY (secret key), DAAPI_BASE_URL, DAAPI_END_USER_ID,
DAAPI_MCP_READ_ONLY, DAAPI_MCP_RESOURCES.
Docs: https://www.desktopaccountingapi.com/docs/guides/mcp/
`;

function readJson<T>(candidates: string[]): T {
  for (const rel of candidates) {
    const url = new URL(rel, import.meta.url);
    if (existsSync(url)) return JSON.parse(readFileSync(url, 'utf8')) as T;
  }
  throw new Error(`missing ${candidates[0]}`);
}

const argv = process.argv.slice(2);
const opt = (name: string): string | undefined => {
  const i = argv.indexOf(`--${name}`);
  return i >= 0 ? argv[i + 1] : argv.find((a) => a.startsWith(`--${name}=`))?.slice(name.length + 3);
};
const flag = (name: string) => argv.includes(`--${name}`);
const truthy = (v: string | undefined) => !!v && /^(1|true|yes|on)$/i.test(v);

const pkg = readJson<{ version: string }>(['../package.json']);
if (flag('help') || flag('h')) {
  process.stdout.write(HELP);
  process.exit(0);
}
if (flag('version')) {
  process.stdout.write(`${pkg.version}\n`);
  process.exit(0);
}

const catalog = readJson<Catalog>(['./catalog.json', '../generated/catalog.json']);
const env = process.env;
const server = new McpServer({
  catalog,
  version: pkg.version,
  apiKey: env.DAAPI_SECRET_KEY?.trim() || undefined,
  baseUrl: opt('base-url') ?? env.DAAPI_BASE_URL ?? 'https://api.desktopaccountingapi.com',
  endUserId: opt('end-user-id') ?? (env.DAAPI_END_USER_ID || undefined),
  // Not configured: detect a read-only key (packages/mcp/src/tools.ts prepare()).
  // --code-allow-http-gets: Conductor's MCP read-only flag, accepted as an alias of --read-only.
  readOnly: flag('read-only') || flag('code-allow-http-gets') || truthy(env.DAAPI_MCP_READ_ONLY) ? true : env.DAAPI_MCP_READ_ONLY ? false : undefined,
  resources: (opt('resources') ?? env.DAAPI_MCP_RESOURCES ?? '').split(',').map((s) => s.trim()).filter(Boolean),
  docsUrl: env.DAAPI_DOCS_URL || undefined,
  userAgent: `desktopaccountingapi-mcp/${pkg.version} (stdio; node ${process.version}; ${process.platform})`,
});
if (!env.DAAPI_SECRET_KEY) process.stderr.write('desktopaccountingapi-mcp: DAAPI_SECRET_KEY is not set; tools will report the missing key.\n');
await serveStdio(server);
