// Code generated by packages/sdk-generator from packages/mcp/src. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:68a0d76d6b51187adfc66d768eae8e30675b5093f4ae538b0d9c32c905b9bb2d
// Streamable HTTP transport (MCP 2025-03-26 and later), stateless: each POST carries one JSON-RPC
// message (or a batch, for 2025-03-26 clients) and is answered with application/json. No server
// sessions and no server-initiated stream, so GET and DELETE return 405. Web-standard Request and
// Response only (Cloudflare Workers, Node 18+).
//
// Connection configuration (all optional):
//   Authorization: Bearer sk_...          secret key, passed to the API unchanged
//   Daapi-End-User-Id header / ?end_user_id=   default end user
//   ?read_only=true                        hide and refuse writes (a read-only key is the server-enforced control);
//                                          without it, a read-only key is detected and treated the same way
//   x-stainless-mcp-client-permissions     Conductor's read-only header; any value means read_only=true
//   ?resources=invoices,customers          also expose one tool per operation for these resources ("all" for every one)

import type { Catalog } from './catalog.ts';
import { McpServer, PROTOCOL_VERSIONS, type JsonRpcMessage } from './server.ts';

export interface HttpOptions {
  catalog: Catalog;
  version: string;
  apiBaseUrl: string;
  fetch?: typeof fetch;
  docsFetch?: typeof fetch;
  docsUrl?: string;
  /** Extra headers for API requests (for example the caller's IP for per-IP limits). */
  apiHeaders?: Record<string, string>;
  /** Where GET from a browser goes (the setup guide). */
  guideUrl?: string;
}

const MAX_BODY = 1_000_000;
// No CORS headers (security review F9): MCP clients are desktop apps, command-line tools and
// servers, which do not need them. Web pages cannot call this server from a browser, matching the
// API, which accepts browser requests only from the docs "Try it" panel (apps/api/src/cors.ts), so
// a secret key never has a reason to sit in frontend code.
const CORS: Record<string, string> = {};

function json(body: unknown, status = 200, extra: Record<string, string> = {}): Response {
  return new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store', ...CORS, ...extra } });
}

const rpcError = (status: number, code: number, message: string) => json({ jsonrpc: '2.0', id: null, error: { code, message } }, status);

const truthy = (v: string | null | undefined) => !!v && /^(1|true|yes|on)$/i.test(v);

export async function handleMcpRequest(request: Request, o: HttpOptions): Promise<Response> {
  const url = new URL(request.url);
  if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: { Allow: 'POST, GET, OPTIONS' } });
  if (request.method === 'GET' && !(request.headers.get('Accept') ?? '').includes('text/event-stream') && o.guideUrl) {
    return new Response(null, { status: 302, headers: { Location: o.guideUrl, 'Cache-Control': 'no-store' } });
  }
  if (request.method !== 'POST') return json({ jsonrpc: '2.0', id: null, error: { code: -32000, message: 'Method not allowed. This server is stateless: send JSON-RPC messages with POST.' } }, 405, { Allow: 'POST, OPTIONS' });
  const version = request.headers.get('Mcp-Protocol-Version');
  if (version && !PROTOCOL_VERSIONS.includes(version)) return rpcError(400, -32000, `Unsupported MCP protocol version ${version}. Supported: ${PROTOCOL_VERSIONS.join(', ')}.`);
  const type = request.headers.get('Content-Type') ?? '';
  if (!type.includes('application/json')) return rpcError(415, -32000, 'Send Content-Type: application/json.');
  const length = Number(request.headers.get('Content-Length') ?? '0');
  if (length > MAX_BODY) return rpcError(413, -32000, 'Request body too large.');
  const raw = await request.text();
  if (raw.length > MAX_BODY) return rpcError(413, -32000, 'Request body too large.');
  let body: unknown;
  try {
    body = JSON.parse(raw);
  } catch {
    return rpcError(400, -32700, 'Parse error');
  }
  const auth = request.headers.get('Authorization') ?? '';
  const apiKey = /^Bearer\s+(\S+)\s*$/i.exec(auth)?.[1];
  const resources = (url.searchParams.get('resources') ?? '').split(',').map((s) => s.trim()).filter(Boolean);
  const server = new McpServer({
    catalog: o.catalog,
    version: o.version,
    apiKey,
    baseUrl: o.apiBaseUrl,
    endUserId: request.headers.get('Daapi-End-User-Id') ?? url.searchParams.get('end_user_id') ?? undefined,
    // Conductor's read-only MCP header (Stainless client permissions, documented as
    // {"allow_http_gets":true}) is honored so a copied Conductor config stays read-only. Fail
    // closed: the header's presence alone means read-only, whatever its value or read_only.
    readOnly: request.headers.has('x-stainless-mcp-client-permissions') ? true : url.searchParams.has('read_only') ? truthy(url.searchParams.get('read_only')) : undefined,
    resources,
    docsUrl: o.docsUrl,
    fetch: o.fetch,
    docsFetch: o.docsFetch,
    apiHeaders: o.apiHeaders,
    userAgent: `desktopaccountingapi-mcp/${o.version} (hosted)`,
  });
  if (Array.isArray(body)) {
    if (!body.length) return rpcError(400, -32600, 'Invalid Request: empty batch');
    const out = (await Promise.all(body.map((m) => server.handle(m)))).filter((r): r is JsonRpcMessage => r !== null);
    return out.length ? json(out) : new Response(null, { status: 202, headers: CORS });
  }
  const res = await server.handle(body);
  return res ? json(res) : new Response(null, { status: 202, headers: CORS });
}
