// Code generated by packages/sdk-generator from packages/mcp/src. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
// Runtime-agnostic MCP server core (no Node-only imports); the tool design is in tools.ts.
export { buildCatalog, defsFor, type Catalog, type CatalogEndpoint, type CatalogParam, type JsonSchema } from './catalog.ts';
export { handleMcpRequest, type HttpOptions } from './http.ts';
export { isValidSecretKey, maskKey } from './key.ts';
export { McpServer, PROTOCOL_VERSIONS, type JsonRpcMessage } from './server.ts';
export { endpointArgsSchema, project, SERVER_NAME, splitDocs, toolName, Tools, type Tool, type ToolOptions, type ToolResult } from './tools.ts';
