// Code generated by packages/sdk-generator from packages/mcp/src. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:68a0d76d6b51187adfc66d768eae8e30675b5093f4ae538b0d9c32c905b9bb2d
// Runtime-agnostic MCP server core (no Node-only imports); the tool design is in tools.ts.
export { buildCatalog, defsFor, type Catalog, type CatalogEndpoint, type CatalogParam, type JsonSchema } from './catalog.ts';
export { handleMcpRequest, type HttpOptions } from './http.ts';
export { isValidSecretKey, maskKey } from './key.ts';
export { McpServer, PROTOCOL_VERSIONS, type JsonRpcMessage } from './server.ts';
export { endpointArgsSchema, project, SERVER_NAME, splitDocs, toolName, Tools, type Tool, type ToolOptions, type ToolResult } from './tools.ts';
