// Code generated by packages/sdk-generator from packages/mcp/src. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:3d102b7bcecbf18e72b655745e5c55d641457fab2fd8184b3da643aeb51bb76f
// Local secret-key check (same rule as the API and SDKs, docs/api-conventions.md section 2):
// `sk_live_`/`sk_test_` + 40 base62 chars, the last 6 being the base62 CRC32 of the first 34.
// Rejecting a mistyped key locally keeps it from counting against the API's per-IP
// failed-authentication limit.

const BASE62 = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
let table: Uint32Array | undefined;

function crc32(input: string): number {
  if (!table) {
    table = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
      let c = n;
      for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
      table[n] = c >>> 0;
    }
  }
  let crc = 0xffffffff;
  for (const byte of new TextEncoder().encode(input)) crc = table[(crc ^ byte) & 0xff]! ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

function base62(value: number, width: number): string {
  let out = '';
  let v = value;
  while (v > 0) {
    out = BASE62[v % 62] + out;
    v = Math.floor(v / 62);
  }
  return out.padStart(width, '0');
}

export function isValidSecretKey(key: string): boolean {
  const m = /^sk_(live|test)_([0-9A-Za-z]{40})$/.exec(key);
  return !!m && base62(crc32(m[2]!.slice(0, 34)), 6) === m[2]!.slice(34);
}

/** `sk_live_...` + last 4, safe for messages. */
export function maskKey(key: string): string {
  const prefix = key.startsWith('sk_live_') ? 'sk_live_' : key.startsWith('sk_test_') ? 'sk_test_' : '';
  return prefix ? `${prefix}...${key.slice(-4)}` : 'the provided key';
}
