// Code generated by packages/sdk-generator from packages/mcp/src. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1fc5496cc47b442606ea78c818f94a29798b32785dc14c59e7986e24f10bf332
// Operation search for list_api_endpoints. Words are matched as tokens (case, plurals and
// camelCase/snake_case ignored, a word of 5+ letters also matches the start of a longer one)
// against an operation's name, tag, summary, description, path, query parameter names and the
// values of its required selector parameters (for example the report families' `reportType`:
// `profit_and_loss_standard`, `open_invoices`). Every word must match; common accounting synonyms
// count as the same word. Each result names the selector values that matched, so "profit and
// loss" leads straight to qbd.reports.generalSummary with reportType profit_and_loss_standard.

import type { Catalog, CatalogEndpoint, JsonSchema } from './catalog.ts';

const STOP_WORDS = new Set(['a', 'an', 'and', 'the', 'of', 'for', 'by', 'to', 'in', 'on', 'with', 'or', 'from', 'my', 'our', 'all']);

/** Phrases rewritten before tokenizing. */
const PHRASES: [RegExp, string][] = [
  [/\bp\s*&\s*l\b|\bpnl\b|\bincome statement\b/gi, 'profit loss'],
  [/\ba\s*\/\s*r\b/gi, 'ar'],
  [/\ba\s*\/\s*p\b/gi, 'ap'],
];

/** A query word also matches these words (already stemmed). */
const SYNONYMS: Record<string, string[]> = {
  receivable: ['ar'],
  ar: ['receivable'],
  payable: ['ap'],
  ap: ['payable'],
  unpaid: ['open'],
  outstanding: ['open'],
  overdue: ['aging', 'open'],
  supplier: ['vendor'],
  client: ['customer'],
  product: ['item'],
  service: ['item'],
  staff: ['employee'],
};

function stem(word: string): string {
  if (word.length > 4 && word.endsWith('ies')) return word.slice(0, -3) + 'y';
  if (word.length > 3 && word.endsWith('s') && !word.endsWith('ss')) return word.slice(0, -1);
  return word;
}

/** Lowercase stemmed tokens; splits camelCase, snake_case, kebab-case, dots and slashes. */
export function tokens(text: string): string[] {
  return text
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean)
    .map(stem);
}

/** The words of a search query, without stop words, each with the words it also matches. */
export function queryWords(search: string): string[][] {
  // Phrases are rewritten case-insensitively, but the query keeps its case until tokens() so a
  // camelCase name (qbd.salesOrders.list, generalSummary) splits exactly like the index does.
  let q = search;
  for (const [re, to] of PHRASES) q = q.replace(re, to);
  return tokens(q)
    .filter((w) => !STOP_WORDS.has(w))
    .map((w) => [w, ...(SYNONYMS[w] ?? [])]);
}

interface Field {
  weight: number;
  tokens: Set<string>;
}

export interface SearchEntry {
  endpoint: CatalogEndpoint;
  fields: Field[];
  /** Values of required enum query parameters, for example reportType values. */
  selectors: { param: string; value: string; tokens: Set<string> }[];
}

function enumOf(catalog: Catalog, schema: JsonSchema): string[] {
  const ref = typeof schema.$ref === 'string' ? schema.$ref.split('/').pop() : undefined;
  const target = ref ? catalog.defs[ref] : schema;
  return Array.isArray(target?.enum) ? target.enum.filter((v): v is string => typeof v === 'string') : [];
}

export function searchEntry(catalog: Catalog, e: CatalogEndpoint): SearchEntry {
  const field = (weight: number, ...texts: string[]): Field => ({ weight, tokens: new Set(texts.flatMap(tokens)) });
  const selectors = e.queryParams
    .filter((p) => p.required)
    .flatMap((p) => enumOf(catalog, p.schema).map((value) => ({ param: p.name, value, tokens: new Set(tokens(value)) })));
  return {
    endpoint: e,
    fields: [
      field(3, e.name, e.tag),
      field(2, e.summary),
      { weight: 2, tokens: new Set(selectors.flatMap((s) => [...s.tokens])) },
      field(1, e.group, e.path, e.description, ...e.queryParams.map((p) => p.name)),
    ],
    selectors,
  };
}

const matches = (have: Set<string>, word: string): boolean => {
  if (have.has(word)) return true;
  if (word.length < 5) return false;
  for (const t of have) if (t.startsWith(word)) return true;
  return false;
};
const matchesAny = (have: Set<string>, alternatives: string[]) => alternatives.some((w) => matches(have, w));

export interface SearchHit {
  endpoint: CatalogEndpoint;
  score: number;
  /** Selector values (for example reportType `open_invoices`) that contain every query word, by parameter. */
  selectors: { param: string; values: string[] }[];
}

/** Scores one operation against the query words; null when a word matches nothing. */
export function scoreEntry(entry: SearchEntry, words: string[][]): SearchHit | null {
  let score = 0;
  for (const alternatives of words) {
    let best = 0;
    for (const f of entry.fields) if (f.weight > best && matchesAny(f.tokens, alternatives)) best = f.weight;
    if (!best) return null;
    score += best;
  }
  const full = words.length ? entry.selectors.filter((s) => words.every((alts) => matchesAny(s.tokens, alts))) : [];
  // A selector value holding the whole multi-word query ("profit and loss") outranks scattered
  // matches, but not an operation whose name holds every word ("sales orders": qbd.salesOrders.*).
  if (full.length && words.length > 1) score += 1;
  const byParam = new Map<string, string[]>();
  for (const s of full) byParam.set(s.param, [...(byParam.get(s.param) ?? []), s.value]);
  return { endpoint: entry.endpoint, score, selectors: [...byParam].map(([param, values]) => ({ param, values })) };
}
