// Code generated by packages/sdk-generator from packages/mcp/src. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1fc5496cc47b442606ea78c818f94a29798b32785dc14c59e7986e24f10bf332
// stdio transport: newline-delimited JSON-RPC on stdin/stdout (MCP specification, "stdio").
// Only protocol messages go to stdout; diagnostics go to stderr. Pure Node.js (no Deno, no
// POSIX-only features), so it runs the same on Windows, macOS and Linux.

import { createInterface } from 'node:readline';
import type { McpServer } from './server.ts';

export function serveStdio(server: McpServer, input: NodeJS.ReadableStream = process.stdin, output: NodeJS.WritableStream = process.stdout): Promise<void> {
  const rl = createInterface({ input, crlfDelay: Infinity });
  const write = (msg: unknown) => output.write(`${JSON.stringify(msg)}\n`);
  const pending = new Set<Promise<void>>();
  rl.on('line', (line) => {
    const trimmed = line.trim();
    if (!trimmed) return;
    let msg: unknown;
    try {
      msg = JSON.parse(trimmed);
    } catch {
      write({ jsonrpc: '2.0', id: null, error: { code: -32700, message: 'Parse error' } });
      return;
    }
    // Requests run concurrently; each response carries its id.
    const work = (async () => {
      if (Array.isArray(msg)) {
        const out = (await Promise.all(msg.map((m) => server.handle(m)))).filter((r) => r !== null);
        if (out.length) void write(out);
      } else {
        const res = await server.handle(msg);
        if (res) void write(res);
      }
    })().catch((err) => void process.stderr.write(`desktopaccountingapi-mcp: ${err instanceof Error ? err.message : String(err)}\n`));
    pending.add(work);
    void work.finally(() => pending.delete(work));
  });
  return new Promise((resolve) => rl.on('close', () => void Promise.all(pending).then(() => resolve())));
}
